logging.level.root=WARN
logging.level.org.example=INFO

aws.s3.bucket=${S3_BUCKET:athenalite-data-ap-south-1}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.sqs.query-queue-url=${QUERY_QUEUE_URL:https://sqs.ap-south-1.amazonaws.com/157325288169/AthenaLiteQueryQueue}
aws.dynamodb.table=${DYNAMODB_TABLE:AthenaLiteTables}
aws.dynamodb.query-table=${DYNAMODB_QUERY_TABLE:AthenaLiteQueries}
aws.cognito.user-pool-id=${COGNITO_USER_POOL_ID:ap-south-1_lTO2dM2uz}
aws.cognito.client-id=${COGNITO_CLIENT_ID:6l3924hdi92gs0784p9qtjkmdi}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
