logging.level.root=WARN
logging.level.org.example=INFO

aws.s3.bucket=${S3_BUCKET:athenalite-data-ap}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.sqs.query-queue-url=${QUERY_QUEUE_URL:https://sqs.ap-south-1.amazonaws.com/085608568709/AthenaLiteQueryQueue}
aws.dynamodb.table=${DYNAMODB_TABLE:AthenaLiteTables}
aws.dynamodb.query-table=${DYNAMODB_QUERY_TABLE:AthenaLiteQueryMetadata}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
