logging.level.root=WARN
logging.level.org.example=INFO

aws.s3.bucket=${S3_BUCKET:athenalite-data}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.sqs.query-queue-url=${QUERY_QUEUE_URL:}
aws.dynamodb.table=${DYNAMODB_TABLE:AthenaLiteTables}
aws.dynamodb.query-table=${DYNAMODB_QUERY_TABLE:AthenaLiteQueries}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
